### ISSUE TITLE
Bodytext shows required field error

### ISSUE THREAD

**Issue by McKoy61** [cdaecke/md_newsfrontend#14]
Typo3 9.5.9
news 7.3.1
md_newsfrontend 1.1.0

Submitting frontend form not possible, the bodytext is marked as required field, even though it is filled with text. Can someone help?
Thanks!
![req_field_error](https://user-images.githubusercontent.com/18348576/64379353-022c2a80-d02f-11e9-8167-bf2e34109800.png)

**Comment by cdaecke** [comment]
Thanks for reporting this issue. Could you please provide some more information?

- which browser are you using?
- does the error occur when creating a new entry AND when editing the entry?
- did you modify the templates?

**Comment by McKoy61** [comment]
Thanks for the reply.

- Firefox 69.0
- on creating a new entry. Existing entries are not shown, though there are other entries from backend users. 
- yes, but switching back to the original templates makes no change.

The extension eventnews is also installed (thats why I changed the template), but deactivating changes nothing.

**Comment by cdaecke** [comment]
After some testing I realized, that it can happen, that the parsleyJs validations are added to the form before the tinyMCE was loaded. This happens for example, if ext:powermail is installed which uses parsleyJs as well.

The changes in the attached commit make sure, that the validation is added AFTER the tinyMCE is initialized.

This issue is now solved in version 1.1.1 of the extension.

**Comment by sebomoto** [comment]
Hello, i just started trying this extension, and to me it looks like this bug is back.

I am using
TYPO3 8.7.27
md_newsfrontend 1.1.5 (latest for 8.7)

When posting i get "this value ist required" in the bodytext. If i reload the page and save again, posting works.
I have Powermail active, so there might be something wrong with parsley as you found out before.

do you have any idea what i could change to prevent this from happening?

Thanks in advance!

Sebastian

**Comment by cdaecke** [comment]
@sebomoto I don't have a TYPO3 8 running any more. A quick test with TYPO3 9 and md_newsfrontend 2.0.0 works for me. 

Please check the following:

- disable `ext:powermail` and verify if this helps
- if you have added your own templates for `ext:md_newsfrontend`, please try the originals
- check the Javascript console for errors

Don't forget to clear the TYPO3 cache when doing the changes.

Hope this helps to track down you issue. Let me know, if you found the problem.

**Comment by sebomoto** [comment]
Thanks for your quick reply, even though the issue has been long closed!

I will try disabling powermail and also with a v9 or v10 TYPO3 and report back.
